language: minimal
dist: xenial
sudo: false

addons:
  apt:
    packages:
      - ninja-build
      - ccache

cache:
  timeout: 3600
  ccache: true
  directories:
    - $HOME/llvm
    - $HOME/.ccache

stages:
  - Setup
  - Build llvm-cbe 1 (Timeout in 20 min.)
  - Build llvm-cbe 2 (Timeout in 20 min.)
  - Build llvm-cbe 3 (Timeout in 20 min.)
  - Build llvm-cbe 4 (Timeout in 20 min.)
  - Build llvm-cbe 5 (Timeout in 20 min.)
  - Build llvm-cbe 6 (Timeout in 20 min.)
  - Build llvm-cbe 7 (Timeout in 20 min.)
  - Build llvm-cbe 8 (Timeout in 20 min.)
  - Build llvm-cbe 9 (Timeout in 20 min.)
  - Build lli 1 (Timeout in 20 min.)
  - Build lli 2 (Timeout in 20 min.)
  - Build lli 3 (Timeout in 20 min.)
  - Build CBEUnitTests 1 (Timeout in 20 min.)
  - Build CBEUnitTests 2 (Timeout in 20 min.)
  - Build CBEUnitTests 3 (Timeout in 20 min.)
  - Run CBEUnitTests

jobs:
  include:
    - stage: Setup
      install:
        - rm -rf ~/llvm
        - cd ~ && curl -fL http://releases.llvm.org/7.0.1/llvm-7.0.1.src.tar.xz | tar xJf -
        - mv ~/llvm-7.0.1.src ~/llvm
        - ln -s $TRAVIS_BUILD_DIR ~/llvm/projects/llvm-cbe
        - mkdir -p ~/llvm/build
        - cd ~/llvm/build && CC=/usr/lib/ccache/cc CXX=/usr/lib/ccache/c++ cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
      script: true
    - &build-llvm-cbe
      stage: Build llvm-cbe 1 (Timeout in 20 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && timeout 1200 ninja llvm-cbe || true
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 2 (Timeout in 20 min.)
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 3 (Timeout in 20 min.)
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 4 (Timeout in 20 min.)
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 5 (Timeout in 20 min.)
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 6 (Timeout in 20 min.)
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 7 (Timeout in 20 min.)
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 8 (Timeout in 20 min.)
    - <<: *build-llvm-cbe
      stage: Build llvm-cbe 9 (Timeout in 20 min.)
    - &build-lli
      stage: Build lli 1 (Timeout in 20 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && timeout 1200 ninja lli || true
    - <<: *build-lli
      stage: Build lli 2 (Timeout in 20 min.)
    - <<: *build-lli
      stage: Build lli 3 (Timeout in 20 min.)
    - &build-cbe-unit-tests
      stage: Build CBEUnitTests 1 (Timeout in 20 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && ninja CBEUnitTests
    - <<: *build-cbe-unit-tests
      stage: Build CBEUnitTests 2 (Timeout in 20 min.)
    - <<: *build-cbe-unit-tests
      stage: Build CBEUnitTests 3 (Timeout in 20 min.)
    - stage: Run CBEUnitTests
      install:
        - test -f ~/llvm/build/projects/llvm-cbe/unittests/CWriterTest
      script:
        - ~/llvm/build/projects/llvm-cbe/unittests/CWriterTest
