language: minimal
dist: xenial
sudo: false

addons:
  apt:
    packages:
      - ninja-build
      - ccache

cache:
  - ccache
  - directories:
      - $HOME/llvm
      - $HOME/.ccache

jobs:
  include:
    - stage: Setup
      install:
        - rm -rf ~/llvm
        - cd ~ && curl -fL http://releases.llvm.org/7.0.1/llvm-7.0.1.src.tar.xz | tar xJf -
        - mv ~/llvm-7.0.1.src ~/llvm
        - ln -s $TRAVIS_BUILD_DIR ~/llvm/projects/llvm-cbe
        - mkdir -p ~/llvm/build
        - cd ~/llvm/build && CC=/usr/lib/ccache/cc CXX=/usr/lib/ccache/c++ cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
      script: true
    - stage: Build llvm-cbe 0 (Timeout in 1 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && timeout 60 ninja llvm-cbe || true
    - stage: Build llvm-cbe 1 (Timeout in 30 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && timeout 1800 ninja llvm-cbe || true
    - stage: Build llvm-cbe 2 (Timeout in 30 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && timeout 1800 ninja llvm-cbe || true
    - stage: Build llvm-cbe 3 (Timeout in 30 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && timeout 1800 ninja llvm-cbe || true
    - stage: Build llvm-cbe 4 (Timeout in 30 min.)
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && timeout 1800 ninja llvm-cbe || true
    - stage: Build lli
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && ninja lli
    - stage: Build CBEUnitTests
      install:
        - test -d ~/llvm/build
      script:
        - cd ~/llvm/build && ninja CBEUnitTests
    - stage: Run CBEUnitTests
      install:
        - test -f ~/llvm/build/projects/llvm-cbe/unittests/CWriterTest
      script:
        - ~/llvm/build/projects/llvm-cbe/unittests/CWriterTest
